# Generated by Django 6.0.7 on 2026-08-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_post_last_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('matricnumber', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
